// <auto-generated />
using System;
using Cocktails.API.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cocktails.API.Migrations
{
    [DbContext(typeof(CocktailContext))]
    [Migration("20210501104201_Migration 1.0")]
    partial class Migration10
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("Cocktails.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Old fashioned"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Classic"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Strong"
                        });
                });

            modelBuilder.Entity("Cocktails.API.Models.Cocktail", b =>
                {
                    b.Property<Guid>("CocktailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Alcoholic")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CocktailId");

                    b.ToTable("Cocktails");
                });

            modelBuilder.Entity("Cocktails.API.Models.CocktailCategory", b =>
                {
                    b.Property<Guid>("CocktailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("CocktailId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CocktailCategories");
                });

            modelBuilder.Entity("Cocktails.API.Models.CocktailImage", b =>
                {
                    b.Property<Guid>("CocktailImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CocktailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CocktailImageId");

                    b.HasIndex("CocktailId");

                    b.ToTable("CocktailImages");
                });

            modelBuilder.Entity("Cocktails.API.Models.CocktailIngredient", b =>
                {
                    b.Property<Guid>("CocktailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CocktailId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("CocktailIngredients");
                });

            modelBuilder.Entity("Cocktails.API.Models.Ingredient", b =>
                {
                    b.Property<Guid>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AlcoholPercentage")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("Cocktails.API.Models.IngredientImage", b =>
                {
                    b.Property<Guid>("IngredientImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IngredientImageId");

                    b.HasIndex("IngredientId");

                    b.ToTable("IngredientImages");
                });

            modelBuilder.Entity("Cocktails.API.Models.CocktailCategory", b =>
                {
                    b.HasOne("Cocktails.API.Models.Category", "Category")
                        .WithMany("CocktailCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cocktails.API.Models.Cocktail", null)
                        .WithMany("CocktailCategories")
                        .HasForeignKey("CocktailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Cocktails.API.Models.CocktailImage", b =>
                {
                    b.HasOne("Cocktails.API.Models.Cocktail", null)
                        .WithMany("Images")
                        .HasForeignKey("CocktailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cocktails.API.Models.CocktailIngredient", b =>
                {
                    b.HasOne("Cocktails.API.Models.Cocktail", null)
                        .WithMany("CocktailIngredients")
                        .HasForeignKey("CocktailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cocktails.API.Models.Ingredient", "Ingredient")
                        .WithMany("CocktailIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Cocktails.API.Models.IngredientImage", b =>
                {
                    b.HasOne("Cocktails.API.Models.Ingredient", null)
                        .WithMany("Images")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cocktails.API.Models.Category", b =>
                {
                    b.Navigation("CocktailCategories");
                });

            modelBuilder.Entity("Cocktails.API.Models.Cocktail", b =>
                {
                    b.Navigation("CocktailCategories");

                    b.Navigation("CocktailIngredients");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("Cocktails.API.Models.Ingredient", b =>
                {
                    b.Navigation("CocktailIngredients");

                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
