version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Ff123456"
      ACCEPT_EULA: "Y"
    ports: 
      - 1433:1433 
    volumes: 
        - ./data:/var/opt/mssql/data
  api:
    image: cocktailapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment: 
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - 5000:5000
      - 5001:5001
    depends_on: 
      - db